### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by aaaaahaaaaa** [stegano/next-http-proxy-middleware#21]
First of all: nice lib. AFAICT it's the only clean middleware out there that allows to update the request's headers with NextJS without errors.

I do encounter issues with your middleware though.

I have a fairly simple proxy setup for an API with a dynamic route (using `SWR` on the client side):
```ts
import type { NextApiRequest, NextApiResponse } from 'next'
import jwt from 'next-auth/jwt'
import httpProxyMiddleware from 'next-http-proxy-middleware';

export default async (req: NextApiRequest, res: NextApiResponse) => {
  const { accessToken } = await jwt.getToken({ req: req, secret: "CHANGE_ME" })
  return httpProxyMiddleware(req, res, {
    target: 'https://whatever.com',
    pathRewrite: { "^/before": '/after' },
    headers: { Authorization: `Bearer ${accessToken}` },
  })
}
```

When sending requests via to the proxy for with the **same path**, it works nicely. When requests with **different paths** go through the middleware, I see the following error (not right away, after a couple of minutes):
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:278:15)
    at write_ (node:_http_outgoing:718:11)
    at ClientRequest.write (node:_http_outgoing:677:15)
    at ProxyServer.<anonymous> (.../next-http-proxy-middleware/build/index.js:1:2419)
    at ProxyServer.emit (.../eventemitter3/index.js:210:27)
    at ClientRequest.<anonymous> (.../http-proxy/lib/http-proxy/passes/web-incoming.js:133:16)
    at ClientRequest.emit (node:events:388:22)
    at tickOnSocket (node:_http_client:781:7)
    at onSocketNT (node:_http_client:820:5)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

And prior to that, NextJS's server shows this kind of warning:
```
[...]
API resolved without sending a response for some/target/url, this may result in stalled requests
[...]
```

**Comment by stegano** [comment]
Hi @aaaaahaaaaa,
Thanks for your reporting 😀
Could you let me know your code snippet of making request
(or HTTP request packets captured using tcpdump)

**Comment by FDiskas** [comment]
Try like so
```ts
import type { NextApiRequest, NextApiResponse } from 'next'
import jwt from 'next-auth/jwt'
import httpProxyMiddleware from 'next-http-proxy-middleware';

export default async (req: NextApiRequest, res: NextApiResponse) => {
  const { accessToken } = await jwt.getToken({ req: req, secret: "CHANGE_ME" })
  await httpProxyMiddleware(req, res, {
    target: 'https://whatever.com',
    pathRewrite: { "^/before": '/after' },
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  res.end();
}
```
The main problem is that response is not finished

**Comment by FDiskas** [comment]
Related https://github.com/vercel/next.js/issues/10439

**Comment by aaaaahaaaaa** [comment]
Thanks for the feedback. Unfortunately I changed my implementation and have no means to test this at the moment. I'll close this issue.

**Comment by stegano** [comment]
This issue may have been resolved by #24.

**Comment by FDiskas** [comment]
v^1.0.10 - still getting 
> this may result in stalled requests.

**Comment by OliverDudgeon** [comment]
Also getting `API resolved without sending a response for some/target/url, this may result in stalled requests` type issues with a similar setup.

**Comment by FDiskas** [comment]
I added
```
export​ ​const​ ​config​ ​=​ ​{​
    ​api​: ​{​
        ​bodyParser​: ​false​,​
        ​externalResolver​: ​true​,​
    ​}​,​
​}​;​
```
On top of file and thous errors is not displayed anymore, but not sure is the problem is solved that way

**Comment by stegano** [comment]
@all-contributors please add @FDiskas for doc
