### ISSUE TITLE
Multiple rewrites not supported

### ISSUE THREAD

**Issue by tgrassl** [stegano/next-http-proxy-middleware#39]
Hi,

There's an error in the rewritePath method. It already returns after the first replacement and thus never checks other rewrites.

**Example:** 
Wrong: rewritePath('/api/test/xy/', { '/$': '', '^/api/test/': '' }) -> /api/test/xy
Correct: rewritePath('/api/test/xy/', { '/$': '', '^/api/test/': '' }) -> xy

```js
export const rewritePath = (
  url: string,
  pathRewrite: { [key: string]: string }
) => {
  for (let patternStr in pathRewrite) {
    const pattern = RegExp(patternStr);
    const path = pathRewrite[patternStr];
    if (pattern.test(url as string)) {
      return url.replace(pattern, path); <--- returns to early
    }
  }
  return url;
};
```

possible fix:

```js
export const rewritePath = (url: string, pathRewrite: { [key: string]: string }): string => {
  let rewrittenUrl = url;
  for (let patternStr in pathRewrite) {
    const pattern = new RegExp(patternStr);
    const path = pathRewrite[patternStr];
    if (pattern.test(url as string)) {
      rewrittenUrl = rewrittenUrl.replace(pattern, path);
    }
  }
  return rewrittenUrl;
};

```

**Comment by stegano** [comment]
Hi @tgrassl 
Thanks for your reporting

Cases like the above issue can happen enough, and I agree. 

In the above case, since `pathRewrite` is an `object(map)` type that does not guarantee the order, different results may be produced depending on the nodejs version or execution environment.

To solve the above issue, in the next version, we plan to modify the `rewritePath` argument value to be passed as an object or an array so that the entered rule can be applied first.

Thanks 😄

**Comment by stegano** [comment]
@all-contributors please add @lorenzodejong for bug

**Comment by stegano** [comment]
@all-contributors please add @tgrassl for bug

**Comment by stegano** [comment]
I just released a package.

You can now use it like this(Pattern checks are run in the order they are entered into the array first.)
```typescript
// pages/[...all].ts
...
export default (req: NextApiRequest, res: NextApiResponse) => (
  isDevelopment
    ? httpProxyMiddleware(req, res, {
      // You can use the `http-proxy` option
      target: 'https://www.example.com',
      // In addition, you can use the `pathRewrite` option provided by `next-http-proxy-middleware`
      pathRewrite: [{
        patternStr: '^/api/new',
        replaceStr: '/v2'
      }, {
        patternStr: '^/api',
        replaceStr: ''
      }],
    })
    : res.status(404).send(null)
);
```
