### ISSUE TITLE
Add support for custom `onProxyReq` and `onProxyRes`

### ISSUE THREAD

**Issue by amaurym** [stegano/next-http-proxy-middleware#50]
I think it would be useful to add `onProxyReq` and `onProxyRes` options in the constructor function:

```diff
httpProxyMiddleware(req, res, {
      // You can use the `http-proxy` option
      target: 'https://www.example.com',
      // In addition, you can use the `pathRewrite` option provided by `next-http-proxy-middleware`
      pathRewrite: [{
        patternStr: '^/api/new',
        replaceStr: '/v2'
      }, {
        patternStr: '^/api',
        replaceStr: ''
      }],
+     onProxyReq: (proxyReq, req, res) => {...},
+     onProxyRes: (proxyRes, req, res) => {...},
    })
```

This will allow more fine-grained request and response rewriting.

**Comment by stegano** [comment]
Hi @amaurym 
Please see https://github.com/stegano/next-http-proxy-middleware/pull/31
Thanks :)

**Comment by amaurym** [comment]
#31 seems to solve onProxyReq, thanks.

How about onProxyRes?

If I do:

```ts
async function handler(req: NextApiRequest, res: NextApiResponse): Promise<void> {
	return httpProxyMiddleware(req, res, {
		target: TARGET_HOST,
	})
	.then(() => {
		res.setHeader(...);
	})
}
```

then I get ` Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

**Comment by stegano** [comment]
Hi @amaurym 

Added `onProxyInit` to options in v1.2.0 version.
You can directly access the `proxy` instance using the `onProxyInit` function.
See the example below.
```ts
...
export default (req: NextApiRequest, res: NextApiResponse) => (
   isDevelopment
     ? httpProxyMiddleware(req, res, {
       ...
       onProxyInit: (proxy) => {
         // @see https://www.npmjs.com/package/http-proxy#listening-for-proxy-events
         proxy.on('onProxyRes', () => {...})
       }
     })
     : res.status(404).send(null)
);
```

Thanks 😀

**Comment by stegano** [comment]
Hi @amaurym
From v1.2.0 version, you can access the `http-proxy` instance through an option. Please refer to the document. 😀
https://github.com/stegano/next-http-proxy-middleware#onproxyinit-option

**Comment by amaurym** [comment]
Sounds good, thanks
