### ISSUE TITLE
Can I transfer cooki through  next-http-proxy-middleware ?

### ISSUE THREAD

**Issue by 4fasl4** [stegano/next-http-proxy-middleware#61]
I have already installed  next-http-proxy-middleware and using it on my nextjs app to connect it to my nodejs express which is on another domain. My express API is using JWT cookie for sign in/sign out . I am trying to transfer it to front-end but no chance . Is this possible ?
This is my current setup :
```
import { NextApiRequest, NextApiResponse } from "next";
import httpProxyMiddleware from "next-http-proxy-middleware";
export default (req: NextApiRequest, res: NextApiResponse) =>
  httpProxyMiddleware(req, res, {
    target: "http://my-nodejs-api-example.herokuapp.com",  changeOrigin: true,
    pathRewrite: {
      "^/api/": '/api/v1/',
    },
  });
```

**Comment by stegano** [comment]
Hi @4fasl4 
try it 
```ts
export default (req: NextApiRequest, res: NextApiResponse) =>
  httpProxyMiddleware(req, res, {
    target: "http://my-nodejs-api-example.herokuapp.com",
    changeOrigin: true,
    headers: {
      authorization: req.headers['authorization']
    },
    pathRewrite: {
      "^/api/": "/api/v1/",
    },
  });

```

**Comment by 4fasl4** [comment]
> 
> You can use the http-proxy options
> 
>     * https://github.com/stegano/next-http-proxy-middleware#features
> 
>     * https://www.npmjs.com/package/http-proxy#options

Thanks for the reply . I just solved it with the cookieDomainRewrite option .
