### ISSUE TITLE
Can this be used in production?

### ISSUE THREAD

**Issue by vincent-thomas** [stegano/next-http-proxy-middleware#72]
Can this be used in production? We have an next.js app and a nestjs server. We have cookies running to and from both of them so different domains are a problem. This seems to fix this issue. Is this stable enough to be used in production?

**Comment by stegano** [comment]
Hi @vincent-thomas 

In my case, I haven't found a problem by applying it to the product yet, and there doesn't seem to be any issues reported.

If possible, consider handling via CORS or Ingress first, and use this library as a last resort. In my opinion nodejs server doesn't look good in terms of performance.

Thanks :)

**Comment by vincent-thomas** [comment]
> Hi @vincent-thomas 
> 
> In my case, I haven't found a problem by applying it to the product yet, and there doesn't seem to be any issues reported.
> 
> If possible, consider handling via CORS or Ingress first, and use this library as a last resort. In my opinion nodejs server doesn't look good in terms of performance.
> 
> Thanks :)

Hi! Thank you for your response! We have now come to an conclusion.
