### ISSUE TITLE
Eliminate slash at the end of the path

### ISSUE THREAD

**Issue by mpinedami** [stegano/next-http-proxy-middleware#73]
Hello,

I need help and it is that when requesting an endpoint that ends in slash (backend in Django Rest Framework) the proxy removes the slash when I put it in the fetch url.

A solution would be to remove the slash in django rest framework and set APPEND_SLASH = False but I lose the redirection when the request is made with the slash.

`RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/auth/jwt/create/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.`

**Comment by stegano** [comment]
Hi @mpinedami 

Sorry, I didn't quite understand your question. Does it mean that the slash of 'endpoint URL' is being removed from this library?

Please see https://nextjs.org/docs/api-reference/next.config.js/trailing-slash
I hope it will help you solve your problem.

Thanks :)
