### ISSUE TITLE
How to pass self response data with selfHandleResponse in NextJS

### ISSUE THREAD

**Issue by phatify** [stegano/next-http-proxy-middleware#80]
I want to handle the self response data (I want to do something like set a some data to cookie, etc...) in Next.js API Routes,  but if I set it to true, none of the webOutgoing passes are called, that resulted in my request never being responded. What should I do?

```
    const handleProxyInit = (proxy) => {
        proxy.on('proxyRes', (proxyRes, req, res) => {
            let body = [];

            proxyRes.on('data', function (chunk) {
                body.push(chunk);
            });
            proxyRes.on('end', function () {
                body = Buffer.concat(body).toString('utf8');
                // do something here
            });
        });
    };

    httpProxyMiddleware(req, res, {
        ...,
        selfHandleResponse: true,
        changeOrigin: true,
        onProxyInit: handleProxyInit,
    });
```

**Comment by stegano** [comment]
Hi @phatify 

Try this
```ts
    const handleProxyInit = (proxy) => {
        proxy.on('proxyRes', (proxyRes, req, res) => {
            let body = [];

            proxyRes.on('data', function (chunk) {
                body.push(chunk);
            });
            proxyRes.on('end', function () {
                body = Buffer.concat(body).toString('utf8');
                // do something here
                res.end(body); // <- Added
            });
        });
    };

    httpProxyMiddleware(req, res, {
        ...,
        selfHandleResponse: true,
        changeOrigin: true,
        onProxyInit: handleProxyInit,
    });
```

If you enable the `selfHandleResponse` flag provided by http-proxy, it seems that the `end` event handler handled internally by `next-http-proxy-middleware` is ignored.

So you need to call the `res.end` function directly or disable the `selfHandleResponse` flag.

**Comment by stegano** [comment]
🤔 Can you see the response headers?
I think you are missing encoding information in the response header.

**Comment by stegano** [comment]
@phatify 
Can I see your handleProxyInit code?
When converting a buffer to a string, you can specify the encoding type as an argument as shown below.
```ts
buffer.toString('utf-8');
```

**Comment by stegano** [comment]
Try setting `Content-Type` response header. Can i see your expected data?
```ts
    const handleProxyInit = (proxy) => {
        proxy.on('proxyRes', (proxyRes, req, res) => {
            let body = [];

            proxyRes.on('data', function (chunk) {
                body.push(chunk);
            });

            proxyRes.on('end', function () {
                body = Buffer.concat(body).toString('utf8');
                res.setHeader('content-type', 'text/html; charset=utf-8'); // <- Added
                res.end(body);
            });
        });
    };

   ...

```

**Comment by stegano** [comment]
> It seems I have no other way, I would disable the selfHandleResponse flag
@phatify 
Hmm.. Finally, try removing the `accept-encoding` from the request header and sending the request.
I think... the original data is compressed or incorrectly encoded.

**Comment by stegano** [comment]
> @stegano I tried to get decoding response data by `console.log(body)` in `handleProxyInit `and see the result was as I expected. But when it sending to client, this response data still encoding, you can see in this comment: [#80 (comment)](https://github.com/stegano/next-http-proxy-middleware/issues/80#issuecomment-1365657403). my response data from client can't get the expected result

Does this mean that you could see non-crashed data?
`I tried to get decoding response data by console.log(body) in handleProxyInit and see the result was as I expected.`
